on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: franzbischoff/replace_envs@v1
        env:
          CONFLUENT_KSQLDB_ENDPOINT: https://pksqlc-357n2.westeurope.azure.confluent.cloud:443
          CONFLUENT_KSQLDB_API_KEY: DRURH3JDXKVKP3JM
          CONFLUENT_KSQLDB_API_SECRET: oM5WZePpw3Lpcuzf02fW6ykXTjwl4gdYmcJ2/uNirW0zU6EivrD0p1gG7bXLwMVF
        with:
          from_file: 'ksql-migrations.properties'
          to_file: 'ksql-migrations.properties'
          commit: 'false'
      - uses: ./.github/actions/ksqldb-migrations-validate
      - uses: ./.github/actions/ksqldb-migrations-apply
